export enum routesNames {
    ACASA = "ACASA",
    ARTISTI = "ARTISTI",
    ALBUME = "ALBUME",
    STIRI = "STIRI",
    EVENIMENTE = "EVENIMENTE",
    DESPRENOI = "DESPRENOI",
    CONTACT = "CONTACT",
    CONFIDENTIALITATECOOKIES = "CONFIDENTIALITATECOOKIES",
    TERMENICONDITII = "TERMENICONDITII",
    INFORMATIIINTERESPUBLIC = "INFORMATIIINTERESPUBLIC",
    CODCONDUITA ="CODCONDUITA",
}